### ISSUE TITLE
Bad Request 

### ISSUE THREAD

**Issue by TheSainEyereg** [Ya4alex/OrthodromyBuilder#7]
Bad request when query param "count" is 0. Fix asap

**Comment by TheSainEyereg** [comment]
Also latitude and longitude are reversed

**Comment by Ya4alex** [comment]
все исправлено:
1 [Исправлена ошибка с 0 count](https://github.com/Ya4alex/OrthodromyBuilder/commit/34755999ce599725a50d6a0f94d3ce6537e4abdb)
2 [изменение последовательности координат](https://github.com/Ya4alex/OrthodromyBuilder/commit/cf027cd42c9847eece23e3f7a0e605b7d1d622f6)
